### ISSUE TITLE
无法用coockie访问

### ISSUE THREAD

**Issue by STARK1234** [puppylpg/oddish#1]
我操作入下：
在chrome登陆puff，从开发者模式复制coockie至config。
然后报错Keyerror data，我发现是因为，用复制的coockie得到的json为：
{'code': 'Login Required', 'error': '请先登录', 'extra': None}
也就是登陆界面。

**Comment by S1mpl3e** [comment]
> 我操作入下：
> 在chrome登陆puff，从开发者模式复制coockie至config。
> 然后报错Keyerror数据，我发现是因为，用复制的coockie得到的json为：
> {'code'：'Login Required'，'error '：'请先登录'，'extra'：无} 
> 也就是登陆界面。

有同样的问题报错
`File "D:\Chrome download\oddish-master\oddish-master\src\crawl\item_crawler.py", line 88, in crawl_goods_by_price_section
    total_page = root_json['data']['total_page']
KeyError: 'data'
`

**Comment by puppylpg** [comment]
应该是cookie粘的不太对。我在最新的提交里增加了cookie示例，处理了cookie不对的情况下的报错，不再直接报stack信息了：https://github.com/puppylpg/oddish/commit/0f872e242d0b4cc40e4352bfcb3e91687de89d89
可以更新一下代码，或者下载3.2.0 release：https://github.com/puppylpg/oddish/releases/tag/v3.2.0
