### ISSUE TITLE
脚本总不使用本地数据，爬过再运行总会重爬，设置为以天为计算也没用

### ISSUE THREAD

**Issue by gsuckerp** [puppylpg/oddish#12]
而且config里无dollar_to_cny，没有就运行不了，找了半天加上总算能运行
steam的数据无法爬取，错误显示为：服务器积极拒绝（这是在用config自带的proxy时显示
现在又变成timeout了（搜了个免费的proxy
不能再重爬buff了，再爬这号也封了。。。

**Comment by gsuckerp** [comment]
用的uu加速器登的steam市场，是不是proxy选项需要填写uu的代理地址？

**Comment by gsuckerp** [comment]
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='steamcommunity.com', port=443): Max retries exceeded with url: /market/pricehistory/?country=CN&currency=1&appid=730&market_hash_name=StatTrak%E2%84%A2%20MP5-SD%20%
7C%20Desert%20Strike%20%28Battle-Scarred%29 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001DDAA4DCF70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无
法连接。'))

**Comment by gsuckerp** [comment]
啊这。删掉proxy值总算能爬steam history prices 了
但buff还是会重爬，不使用本地数据
而且config里无dollar_to_cny，没有就运行不了

**Comment by puppylpg** [comment]
当天是否重爬是config里的`granularity_hour`控制的，设为false如果当天爬过就不再爬了。

**Comment by puppylpg** [comment]
但是筛选如果条件变更了还是会重爬的，比如饰品爬取范围变了，就会重新爬取

**Comment by gsuckerp** [comment]
> 
> 
> 但是筛选如果条件变更了还是会重爬的，比如饰品爬取范围变了，就会重新爬取

没有变，且granularity_hour 也设置成false了，buff的数据仍会重新爬取
还有config里没有dollar to cny这一项，必须手动加上脚本才能运行

**Comment by puppylpg** [comment]
> > 但是筛选如果条件变更了还是会重爬的，比如饰品爬取范围变了，就会重新爬取
> 
> 没有变，且granularity_hour 也设置成false了，buff的数据仍会重新爬取
> 还有config里没有dollar to cny这一项，必须手动加上脚本才能运行

上次改成直接从steam获取人民币价格，所以dollar_to_cny这个配置不再需要了，但是看起来读配置解析汇率的地方忘删了，等我回去删一下。这个用的时候就先手动加配置里吧，实际上应该没用到

**Comment by puppylpg** [comment]
非强制爬取这一点，只要：
1. 条件都没变；
2. granalarity_hour = false, force_crawl = false；
3. 当天爬过。

应该不会重爬了。确定是这样吗？如果设成这样还有问题，我回去也检查一下

**Comment by gsuckerp** [comment]
> 
> 
> 非强制爬取这一点，只要：
> 
>     1. 条件都没变；
> 
>     2. granalarity_hour = false, force_crawl = false；
> 
>     3. 当天爬过。
> 
> 
> 应该不会重爬了。确定是这样吗？如果设成这样还有问题，我回去也检查一下

确定如此
脚本不是先爬取buff的物品列表吗
爬完在log里都会完整保留
但是再运行脚本却不会引用，会再从buff爬一次

**Comment by puppylpg** [comment]
> > 非强制爬取这一点，只要：
> > ```
> > 1. 条件都没变；
> > 
> > 2. granalarity_hour = false, force_crawl = false；
> > 
> > 3. 当天爬过。
> > ```
> > 
> > 
> > 应该不会重爬了。确定是这样吗？如果设成这样还有问题，我回去也检查一下
> 
> 确定如此
> 脚本不是先爬取buff的物品列表吗
> 爬完在log里都会完整保留
> 但是再运行脚本却不会引用，会再从buff爬一次

好的，我回去看一眼。之前不是这样的
