### ISSUE TITLE
有关 dollar_to_cny 的问题

### ISSUE THREAD

**Issue by S1mpl3e** [puppylpg/oddish#2]
现行下获取取得st价格数据可能已经是人民币价格数据
当赋予`dollar_to_cny = 7`时 只会使价格凭空翻七倍（惊喜 以为暴富）
试验得 赋予`dollar_to_cny = 1`时价格大致正确（落空 怒关steam）

另 感谢大作 作者牛逼

**Comment by puppylpg** [comment]
不会吧，我又确认了一下，原始数据确实爬的是美元。确实应该用7这个汇率。

你搞的数据让我看一眼？

**Comment by S1mpl3e** [comment]
[赋值1.txt](https://github.com/puppylpg/oddish/files/4582942/1.txt)
[按汇率赋值.txt](https://github.com/puppylpg/oddish/files/4582943/default.txt)
 前几天的数据
等会再跑个小型的试试

**Comment by S1mpl3e** [comment]
> 不会吧，我又确认了一下，原始数据确实爬的是美元。确实应该用7这个汇率。
> 
> 你搞的数据让我看一眼？

[赋值1.txt](https://github.com/puppylpg/oddish/files/4582955/1.txt)
[按汇率赋值.txt](https://github.com/puppylpg/oddish/files/4582957/default.txt)
前几天的数据了
过会再跑个小型的再测试一下

**Comment by silentnoname** [comment]
应该和buff账号设置的货币单位有关系

**Comment by S1mpl3e** [comment]
> 应该和buff账号设置的货币单位有关系

我确实设置的是人民币 有可能是这个导致的
