### ISSUE TITLE
老哥我环境装好了但是控制台总是弹出这些信息

### ISSUE THREAD

**Issue by Radra9** [puppylpg/oddish#3]
Traceback (most recent call last):
  File "C:\Users\Am6zingDavid\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Am6zingDavid\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\oddish-master\src\__main__.py", line 3, in <module>
    from src.crawl import item_crawler
  File "E:\oddish-master\src\crawl\item_crawler.py", line 5, in <module>
    from src.crawl import history_price_crawler
  File "E:\oddish-master\src\crawl\history_price_crawler.py", line 3, in <module>
    from src.util import requester
  File "E:\oddish-master\src\util\requester.py", line 11, in <module>
    k, v = line.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Radra9** [comment]
老哥能帮忙看一下么

**Comment by puppylpg** [comment]
cookies粘的有问题。完整的cookie是这种
```
cookie = _ga=GA1.2.162602080.1551374933; _ntes_nuid=8ce0cf6bdce55512e73f49cb8a49960e; mail_psc_fingerprint=d80ec72871726e9b192181fd1a3633d6; usertrack=CrH5y11BrGaqLV9AAwiDAg==; OUTFOX_SEARCH_USER_ID_NCOO=29659292.15961449; Device-Id=33u998YqmNWbhH5GbWUo; nts_mail_user=thingsregister@163.com:-1:1; vjuids=369cb7d82.170e16a9519.0.3eb2c52902997; vjlast=1584329824.1584329824.30; _ntes_nnid=8ce0cf6bdce55512e73f49cb8a49960e,1584329823520; vinfo_n_f_l_n3=d81bf3a25989eb31.1.4.1561837557589.1576393349946.1585037711031; Locale-Supported=zh-Hans; game=csgo; _gid=GA1.2.1702930120.1587149242; _gat_gtag_UA_109989484_1=1; NTES_YD_SESS=34x46B3WLcHNzYLC080xKTcZqiRBZYn83NUgr59KrGQWCIEACNjlM8xycrh52GLtfEIb3cRk11tYtfGaivR47i.jL7gDQQAMaRqR8phNC0Y570AajOkjhFgRpNI.WK08chW33p990sKj83gxNfT1_qgPRMYdzEQgwjQl5ZRSTZnKaZHtOmpTs.l3CiS3_ZOfSMMm7ZLnadyah8wwMWRWNWQ0bzVryOGrlfUT0KtBHfLa_; S_INFO=1587149270|0|3&80##|573988092051; P_INFO=573988092051|1587149270|1|netease_buff|00&99|bej&1586173388&netease_buff#bej&null#10#0#0|&0|null|573988092051; session=1-dcjSrPQBIdmY6HdaQFexH7OZSVaMx-TH62Du31AF6Z4G2046524528; csrf_token=IjVlNDJmNjk5OGJlMzg0Y2Q3MTgxYmI5NTliZDQyNzVkZTUyNjI0Njki.EXuLYQ.grA9q0_gRaRxvLSEqMD4fEbCihI
```
我在配置文件里写的a=b;c=d等等这种格式

**Comment by dimogu** [comment]
[BASIC]
# 网页登录buff后，把浏览器的cookie贴到这里，才能运行。推荐从Chrome中复制，下面是一条示例cookie
cookie = _ga=GA1.2.1258881027.1577182902; _ntes_nnid=a4a9083c6466670e6c0d248bd76ed140,1578469498967; _ntes_nuid=a4a9083c6466670e6c0d248bd76ed140; __root_domain_v=.163.com; _qddaz=QD.aszclo.t4wh4n.k7ozwui8; mail_psc_fingerprint=693fe5e41015a01ab0af03fef9e39375; NTES_CMT_USER_INFO=276612171%7C%E6%9C%89%E6%80%81%E5%BA%A6%E7%BD%91%E5%8F%8B0gvchb%7Chttp%3A%2F%2Fcms-bucket.nosdn.127.net%2F2018%2F08%2F13%2F078ea9f65d954410b62a52ac773875a1.jpeg%7Cfalse%7CcGt0a3d4cEAxNjMuY29t; nts_mail_user=leiaoben434200@163.com:-1:1; vinfo_n_f_l_n3=f0e812d617da9328.1.12.1578469499015.1584447059937.1589356895271; Locale-Supported=zh-Hans; game=csgo; _gid=GA1.2.1398617832.1589465989; S_INFO=1589471776|0|3&80##|18567652860; P_INFO=18567652860|1589471776|1|netease_buff|00&99|null&null&null#hen&410300#10#0|&0||18567652860; csrf_token=ImNlODJiNTk0ZTllZTc0MzUwMDQxMGNlMGI0MGJmMThiMzFjZjljZGQi.EZ78ew.Wjg8WwiT2jo3qUT9W1WWFd9pPCY

# 控制程序行为
[BEHAVIOR]
# 按小时保存数据？如果为True，且该小时已经爬过，则不再爬取，直接用上次爬后保存的数据
# 如果为False，则单位为天，即当天如果已经爬过网站，再次运行时不再爬取，直接使用本地数据
granularity_hour = True
# 不管本地有没有数据，只要运行就强制爬取网站
force_crawl = False
# 一次请求的超时重试次数
retry_times = 3

# 基本参数设置
[COMMON]
# 美元兑人民币汇率
dollar_to_cny = 7.0
# steam扣税比例
steam_sell_tax = 0.15

# 过滤行为
[FILTER]
# 爬取物品的最低价格，价格过低则不考虑
crawl_min_price_item = 100
# 爬取物品的最高价格
crawl_max_price_item = 200
# 7天交易历史，少于该阈值则认为是冷门物品，不考虑
min_sold_threshold = 70
# 爬取类别白名单，如只想爬取AK和M4（A1 & A4），则设置为：["weapon_ak47", "weapon_m4a1", "weapon_m4a1_silencer"]
# 具体类别参考`config/reference/category.md`，详见README
category_white_list = []
# 爬取类别黑名单。如果黑名单白名单同时存在，白名单优先级更高
# 默认的黑名单加了以下内容，排除掉乱七八糟的武器箱音乐盒印花探员之类的
category_black_list = ["csgo_type_tool", "csgo_type_spray", "csgo_type_collectible", "csgo_type_ticket", "csgo_tool_gifttag", "csgo_type_musickit", "csgo_type_weaponcase", "csgo_tool_weaponcase_keytag", "type_customplayer"]

# 结果设置
[RESULT]
# 每一项建议只显示这么多条数据
top_n = 50

**Comment by dimogu** [comment]
C:\Users\Administrator\Downloads\Compressed\oddish-master>python -m src
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Downloads\Compressed\oddish-master\src\__main__.py", line 3, in <module>
    from src.crawl import item_crawler
  File "C:\Users\Administrator\Downloads\Compressed\oddish-master\src\crawl\item_crawler.py", line 3, in <module>
    from src.config.definitions import *
  File "C:\Users\Administrator\Downloads\Compressed\oddish-master\src\config\definitions.py", line 15, in <module>
    config.read(CONFIG_PATH, encoding='utf-8')
  File "D:\python\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "D:\python\lib\configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\Administrator\\Downloads\\Compressed\\oddish-master\\config\\config.ini', line: 1
'\ufeff[BASIC]\n'
