### ISSUE TITLE
关于读取cache时的异常判断

### ISSUE THREAD

**Issue by RaymondMcGuire** [puppylpg/oddish#31]
今天再跑程序的时候，不知道为什么存储缓存文件地方出了问题。
而后重新开程序的时候就会在这个地方报错（原因是存在cache文件内容却是空，我把那个空的缓存文件删掉就可以运行了），
这个地方可能需要进行一下异常判断如果存在缓存文件但是格式不对之类的时候进行处理。

> def fetch(url):
       urlid = url_id(url)
       log.info('Successful attempt to fetch from {}'.format(urlid))
       with open(os.path.join(cache_root, urlid), "r", encoding='utf-8') as f:
           return f.read()

**Comment by ccinv** [comment]
现在会检查是否为合法的 json 格式，除了一些极端状况之外应该都没事了。
