### ISSUE TITLE
提个加到说明里的建议

### ISSUE THREAD

**Issue by XianUex** [puppylpg/oddish#32]
# 建议描述
每次爬取有延迟也会封号的，而且是不会自己解封的那种冻结。爬BUFF数据真的不要用大号，否则会非常麻烦... 惨痛教训

**Comment by XianUex** [comment]
另外 一个账号冻结之后 登陆小号并在配置文件中更换cookie 运行结果仍然是报错冻结 在重新下载后恢复正常。

**Comment by ccinv** [comment]
你使用的是最新版本吗？我把steam历史价格来源更换为SCM后爬取了数十次并且用的是最低限度延迟，没有被封过号（即使我那个账号以前被封过，应该是被盯上的）。

**Comment by puppylpg** [comment]
> 另外 一个账号冻结之后 登陆小号并在配置文件中更换cookie 运行结果仍然是报错冻结 在重新下载后恢复正常。

重新下载指的是下载最新代码？现在的代码应该不会有封号的问题，基本不在buff上爬什么东西了

**Comment by hooohoooh** [comment]
昨晚以4秒间隔爬了两小时被buff暂时封号了，不过好在过了约12小时就解封了
