### ISSUE TITLE
貌似steam增加了新的反爬机制？

### ISSUE THREAD

**Issue by wbsddgg** [puppylpg/oddish#38]
# 问题描述
day 7， 仍旧没能运行成功哈哈 。希望总有一天我可以完美运行一次。

我把重试次数设置成0 然后很快就爬完了 **给了5个建议 cmd可以看到 都是是P2000枪支，**

sugesstion txt的就是下面信息 啥也没有

After threshold(history_sold >= 70) filtered: 
       price  sell_num  steam_predict_price  buy_max_price  gap  gap_percent  history_sold  history_days  average_sold_price  average_sold_price_after_tax
count    0.0       0.0                  0.0            0.0  0.0          0.0           0.0           0.0                 0.0                           0.0
mean     NaN       NaN                  NaN            NaN  NaN          NaN           NaN           NaN                 NaN                           NaN
std      NaN       NaN                  NaN            NaN  NaN          NaN           NaN           NaN                 NaN                           NaN
min      NaN       NaN                  NaN            NaN  NaN          NaN           NaN           NaN                 NaN                           NaN
25%      NaN       NaN                  NaN            NaN  NaN          NaN           NaN           NaN                 NaN                           NaN
50%      NaN       NaN                  NaN            NaN  NaN          NaN           NaN           NaN                 NaN                           NaN
75%      NaN       NaN                  NaN            NaN  NaN          NaN           NaN           NaN                 NaN                           NaN
max      NaN       NaN                  NaN            NaN  NaN          NaN           NaN           NaN                 NaN                           NaN

收益降序：

# 复现步骤

# 报错信息

# 相关截屏（最好贴一下）

# 软件信息
请完善以下信息：
- python版本：
- oddish版本（tag或者commit id）： 比如v3.6.1或者b3fcf3be37ecf58c955904a258f97a66b01b0db6；
- 操作系统：比如Windows 10；

**Comment by puppylpg** [comment]
哈哈哈，老哥真实坚持不懈呀，辛苦了

这个NaN的问题和你上个issue应该一样，还是没爬到数据导致的

我也增加了一些校验，数据为空时就输出建议了

还是那句话，代理不行是真没办法
😢

**Comment by wbsddgg** [comment]
> 
> 
> 哈哈哈，老哥真实坚持不懈呀，辛苦了
> 
> 这个NaN的问题和你上个issue应该一样，还是没爬到数据导致的
> 
> 我也增加了一些校验，数据为空时就输出建议了
> 
> 还是那句话，代理不行是真没办法
> 😢

哈哈 之所以坚持不懈 还是得谢谢你！因为我看到这个代码的时候 简直太兴奋了，没想到还有这么神奇的东西！！

我现在可以做到打开游戏的加速器，用网页就能点开steam市场，应该代理的问题解决了，只是还是爬不成功暂时。

最近在听老师讲课 已经可以做python猜拳游戏了，总之真的很感谢你，你的代码是我最近这几天学习的动力！！

**Comment by puppylpg** [comment]
> > 哈哈哈，老哥真实坚持不懈呀，辛苦了
> > 这个NaN的问题和你上个issue应该一样，还是没爬到数据导致的
> > 我也增加了一些校验，数据为空时就输出建议了
> > 还是那句话，代理不行是真没办法
> > cry
> 
> 哈哈 之所以坚持不懈 还是得谢谢你！因为我看到这个代码的时候 简直太兴奋了，没想到还有这么神奇的东西！！
> 
> 我现在可以做到打开游戏的加速器，用网页就能点开steam市场，应该代理的问题解决了，只是还是爬不成功暂时。
> 
> 最近在听老师讲课 已经可以做python猜拳游戏了，总之真的很感谢你，你的代码是我最近这几天学习的动力！！

加油，可以看着这个代码多学点儿python的东西，有兴趣学起来就很快了

这代码一开始是我写的，但是后来其他小伙伴的参与让代码的功能和一开始相比有了很大改观。所以谢我一个人真的承受不来。学了python以后如果有想法欢迎贡献代码，成为共同维护者 :v:

**Comment by wbsddgg** [comment]
> 
> 
> > > 哈哈哈，老哥真实坚持不懈呀，辛苦了
> > > 这个NaN的问题和你上个issue应该一样，还是没爬到数据导致的
> > > 我也增加了一些校验，数据为空时就输出建议了
> > > 还是那句话，代理不行是真没办法
> > > cry
> > 
> > 
> > 哈哈 之所以坚持不懈 还是得谢谢你！因为我看到这个代码的时候 简直太兴奋了，没想到还有这么神奇的东西！！
> > 我现在可以做到打开游戏的加速器，用网页就能点开steam市场，应该代理的问题解决了，只是还是爬不成功暂时。
> > 最近在听老师讲课 已经可以做python猜拳游戏了，总之真的很感谢你，你的代码是我最近这几天学习的动力！！
> 
> 加油，可以看着这个代码多学点儿python的东西，有兴趣学起来就很快了
> 
> 这代码一开始是我写的，但是后来其他小伙伴的参与让代码的功能和一开始相比有了很大改观。所以谢我一个人真的承受不来。学了python以后如果有想法欢迎贡献代码，成为共同维护者 ✌️

这个代码太强了 感谢你们的勤劳和智慧，我也终于用上了，安全的买了自己喜欢的游戏，致敬！！！
