### ISSUE TITLE
关于SOCKS以及其他一些问题想请教一下

### ISSUE THREAD

**Issue by 57yn** [puppylpg/oddish#40]
# 问题描述
程序到了查找历史价格的时候出现了大量的报错，如下图。
每次刷新出来的数据都是下图这样的。
代理的话，挂网易UU就可以了吧？
请问下这是什么原因呀？
还有就是程序停止后可以保存当前的数据，并在下次启动时读取这部分数据吗？比如这次的运行已经筛选出了符合价格的皮肤，在下次运行时读取到了进度然后直接进入到分析价格比率的操作。

# 相关截屏（最好贴一下）
![截图20201113181911307](https://user-images.githubusercontent.com/48508742/99061459-8cc9cb80-25dc-11eb-9b68-89f5621355cc.jpg)
![截图20201113181958762](https://user-images.githubusercontent.com/48508742/99061517-a66b1300-25dc-11eb-90b4-620d5f0b310a.jpg)

# 软件信息
- python版本：3.7.4
- oddish版本（tag或者commit id）：2020.11.13下载的
- 操作系统：Windows 10；

**Comment by ccinv** [comment]
研究了下UU的原理，更新了下文档。
> 你也可以使用网易UU加速器，只需使用模式一、二或三加速Steam社区/商店，并将配置文件中的proxy留空。

请测试下这种方法是否可行，注意节点模式的选择。

**Comment by puppylpg** [comment]
> 研究了下UU的原理，更新了下文档。
> 
> > 你也可以使用网易UU加速器，只需使用模式一、二或三加速Steam社区/商店，并将配置文件中的proxy留空。
> 
> 请测试下这种方法是否可行，注意节点模式的选择。

有相关文档或者链接能贴出来看一下吗

**Comment by 57yn** [comment]
> 研究了下UU的原理，更新了下文档。
> 
> > 你也可以使用网易UU加速器，只需使用模式一、二或三加速Steam社区/商店，并将配置文件中的proxy留空。
> 
> 请测试下这种方法是否可行，注意节点模式的选择。

我试了用移动和电信网络去连接UU的模式三都失败了
![1](https://user-images.githubusercontent.com/48508742/99208140-a5afc800-27fa-11eb-9cf4-c03077540864.png)
![2](https://user-images.githubusercontent.com/48508742/99208962-f4f6f800-27fc-11eb-9368-09a0223d418f.png)

UU也只提供了模式三和模式四，连接模式四的节点以后就会出现访问steam市场历史价格超时的问题。程序结束以后输出的文档有内容但是行、列全为空，没有信息。文档忘记保存了没办法截图

**Comment by ccinv** [comment]
所以问题是选择的模式三，UU就不能提供加速？我这里可以连上模式三，如果真的有这样的问题的话，还是得向UU反馈，这里帮不上忙。

**Comment by 57yn** [comment]
> 所以你连接不上任何一个模式三的UU例程？
> 如果真的有这样的问题的话，还是得向UU反馈，这里帮不上忙。我这是可以连上的。

emmmm，我下班回去了再试试吧，可能是电脑问题

**Comment by ccinv** [comment]
> > 研究了下UU的原理，更新了下文档。
> > 
> > > 你也可以使用网易UU加速器，只需使用模式一、二或三加速Steam社区/商店，并将配置文件中的proxy留空。
> > 
> > 请测试下这种方法是否可行，注意节点模式的选择。
> 
> 有相关文档或者链接能贴出来看一下吗

还真没有，我是通过测试发现前三种模式是类似vpn的，模式四是lsp劫持不能用

**Comment by 57yn** [comment]
周末的时候再次试了下，UU的三模式是可以

**Comment by 57yn** [comment]
这边没问题了，感谢解答
