### ISSUE TITLE
关于user-agent

### ISSUE THREAD

**Issue by puppylpg** [puppylpg/oddish#45]
# 建议描述
一开始图方便，把user-agent写死了，确实不太合适，考虑修改一下。两种想法：
1. 让用户自己配置，就像cookie一样；
2. 继续对用户隐藏，不过往上多找一些user-agent，放入单独的文件，每次爬取从里面随机挑一个user-agent；

对于防止封禁有一定好处。

**Comment by zwwskm** [comment]
大佬好，我有点不明白，普通用户即使使用不同浏览器也不会是同一个cookie吧，每次请求都随机一个UA却是同一个cookie访问不会触发网易的反爬机制吗？感觉就跟同一个账户频繁更换IP一样危险…

**Comment by puppylpg** [comment]
> 大佬好，我有点不明白，普通用户即使使用不同浏览器也不会是同一个cookie吧，每次请求都随机一个UA却是同一个cookie访问不会触发网易的反爬机制吗？感觉就跟同一个账户频繁更换IP一样危险…

嗯，也有道理。我现在改成配置里贴自己的ua，如果不贴，系统随机一个ua出来，本次爬取所有的请求都使用这个ua。这样总比一直用一个写死在代码里的ua好: #55

**Comment by z1y1m1** [comment]
有个fake_useragent包可以考虑，专门干这个用的
