### ISSUE TITLE
steam售价如何调成75分位

### ISSUE THREAD

**Issue by Jccg100047928-gif** [puppylpg/oddish#46]
# 问题描述
因为steam市场很多都是扔给求购，25分位总是比求购价低，所以想改75分位
# 复现步骤

# 报错信息

# 相关截屏（最好贴一下）

# 软件信息
请完善以下信息：
- python版本：
- oddish版本（tag或者commit id）： 比如v3.6.1或者b3fcf3be37ecf58c955904a258f97a66b01b0db6；
- 操作系统：比如Windows 10；

**Comment by puppylpg** [comment]
https://github.com/puppylpg/oddish/blob/7a49969a6ec77ffe9eadd134fa269b2162a6448d/src/data/item.py#L75

25改成75就行了

**Comment by Jccg100047928-gif** [comment]
好的，我试试
