### ISSUE TITLE
suggestion文档为空白

### ISSUE THREAD

**Issue by tobiieyetracker** [puppylpg/oddish#49]
# 问题描述
有log文件，运行也正常，但是suggestion自动创建之后没有内容
# 复现步骤

# 报错信息

# 相关截屏（最好贴一下）

# 软件信息
请完善以下信息：
- python版本：3.8
- oddish版本（tag或者commit id）： v3.8.3
- 操作系统：Windows 10 企业版；

**Comment by puppylpg** [comment]
能贴一下log，或者log的最后一些内容吗（忽略前面一条条爬取的内容），可能是一些限制太高，导致没有符合条件的饰品。比如没有饰品7天卖出70个以上

**Comment by Ricardododo** [comment]
抱歉没看到回复，找到问题了。是设置的限制过于详细，爬了几条之后就停下来了，也没有自动报错。

**Comment by puppylpg** [comment]
好的～
