### ISSUE TITLE
buff返回请先登录

### ISSUE THREAD

**Issue by gsuckerp** [puppylpg/oddish#50]
# 问题描述
使用了正确cookie，buff还是返回请先登录
11月份还可用
# 复现步骤

# 报错信息

# 相关截屏（最好贴一下）

# 软件信息
请完善以下信息：
- python版本：
- oddish版本（tag或者commit id）：最新
- 操作系统：比如Windows 10；

**Comment by puppylpg** [comment]
copy完cookie先别急着关网页，要不然cookie可能过期了。应该是这样，如果cookie没问题的话，其他原因暂时想不到了

**Comment by gsuckerp** [comment]
> 
> 
> copy完cookie先别急着关网页，要不然cookie可能过期了。应该是这样，如果cookie没问题的话，其他原因暂时想不到了

脚本访问被识别出来所以ban了吗

**Comment by gsuckerp** [comment]
> 
> 
> copy完cookie先别急着关网页，要不然cookie可能过期了。应该是这样，如果cookie没问题的话，其他原因暂时想不到了

今天试又好了
