### ISSUE TITLE
不能生成database文件夹

### ISSUE THREAD

**Issue by duhl1999** [puppylpg/oddish#52]
# 问题描述
脚本执行之后，只生成了cache、log、suggestion文件夹，没有生成database
文件夹，我无法看到我爬取的全部数据
# 复现步骤
```
python3 -m src
```
# 报错信息

# 相关截屏（最好贴一下）

# 软件信息
请完善以下信息：
- python版本：3.7.9
- oddish版本（tag或者commit id）： 3.8.3
- 操作系统：ubuntu 20.04 LTS

**Comment by puppylpg** [comment]
database是老版本的代码生成的，新版本生成cache，缓存粒度更小。不过你不用关心这些，看log或者suggestion就行了

**Comment by duhl1999** [comment]
请问我如果想看我爬取到的全部数据应该如何操作

**Comment by puppylpg** [comment]
现在没有database文件应该看不到所有信息了。
如果想看所有数据，配置里有一项显示topN项建议，把那个设的非常大应该能看到所有的信息，可以试试

**Comment by duhl1999** [comment]
好的非常感谢您
之前将所有数据都存储下来的设计我个人认为非常实用，甚至可以替代suggestion
希望在后续更新中可以将这个功能再添加上
非常感谢您写的这个脚本，对我来说非常实用

**Comment by puppylpg** [comment]
> 好的非常感谢您
> 之前将所有数据都存储下来的设计我个人认为非常实用，甚至可以替代suggestion
> 希望在后续更新中可以将这个功能再添加上
> 非常感谢您写的这个脚本，对我来说非常实用

emmm，可以考虑加上，但需求应该比较小，其实我自己都没看过database，hhh，毕竟只看suggestion对我来说就够了

**Comment by ccinv** [comment]
README 里面还留着database 可能会给人带来疑惑

**Comment by puppylpg** [comment]
> README 里面还留着database 可能会给人带来疑惑

ok，我删一下

**Comment by puppylpg** [comment]
> > 好的非常感谢您
> > 之前将所有数据都存储下来的设计我个人认为非常实用，甚至可以替代suggestion
> > 希望在后续更新中可以将这个功能再添加上
> > 非常感谢您写的这个脚本，对我来说非常实用
> 
> emmm，可以考虑加上，但需求应该比较小，其实我自己都没看过database，hhh，毕竟只看suggestion对我来说就够了

考虑了一下，还是不加了。数据万一被用来搞事情，buff可能要砍我们了
