### ISSUE TITLE
是否可以爬DOTA2饰品

### ISSUE THREAD

**Issue by RaymondMcGuire** [puppylpg/oddish#56]
# 问题描述
是否可以爬DOTA2饰品

**Comment by puppylpg** [comment]
这个短期内应该暂不考虑。目前buff对oddish打压的比较厉害，动不动就封号，得先把这个问题解决一下

如果成功解决，后期接入dota也不是不可以

**Comment by RaymondMcGuire** [comment]
> 这个短期内应该暂不考虑。目前buff对oddish打压的比较厉害，动不动就封号，得先把这个问题解决一下
> 
> 如果成功解决，后期接入dota也不是不可以

收到
