### ISSUE TITLE
page size的问题

### ISSUE THREAD

**Issue by zwwskm** [puppylpg/oddish#60]
https://github.com/puppylpg/oddish/blob/cbd27fed314a1192ae16a23547094c2acf2fc989/src/crawl/item_crawler.py#L115

这里应该是总数量除以80，或者原来的页数乘80除20吧…跑了一遍发现每个类别都是只有一页😅

**Comment by puppylpg** [comment]
wtf......

Orz 我错了

**Comment by puppylpg** [comment]
#61
