### ISSUE TITLE
4秒间隔下限

### ISSUE THREAD

**Issue by gsuckerp** [puppylpg/oddish#64]
# 问题描述
怎么爬取间隔下限强制设为4秒了
之前我都是6-11秒爬buff
爬完重开2秒间隔爬steam
这样4秒最低爬steam效率有点低诶😥😥😥
# 复现步骤

# 报错信息

# 相关截屏（最好贴一下）

# 软件信息
请完善以下信息：
- python版本：
- oddish版本（tag或者commit id）： 比如v3.6.1或者b3fcf3be37ecf58c955904a258f97a66b01b0db6；
- 操作系统：比如Windows 10；

**Comment by gsuckerp** [comment]
找到源码了，没事了😂
改成1爬着真爽

**Comment by puppylpg** [comment]
行车不规范，封号两行泪 :rofl: 

最近要上线一个版本，steam十来个请求并发爬取，buff请求间隔拉长，到时候效率会很高，应该是4.0.0，欢迎试用

**Comment by gsuckerp** [comment]
> 
> 
> 行车不规范，封号两行泪 🤣
> 
> 最近要上线一个版本，steam十来个请求并发爬取，buff请求间隔拉长，到时候效率会很高，应该是4.0.0，欢迎试用

可以，我老司机了，爬buff慢慢爬，爬steam能爬多快就爬多快

之前我就建议buff和steam分开爬了😁
