### ISSUE TITLE
请问如果个人编写其他爬虫，steam的请求需要间隔多久？和Buff一样吗？

### ISSUE THREAD

**Issue by Frankcsc** [puppylpg/oddish#72]
RT
请问如果个人编写其他爬虫，steam的请求需要间隔多久？
也可联系邮箱 yulecsc@qq.com
感谢！

**Comment by puppylpg** [comment]
steam貌似没有爬取间隔限制，后来的oddish用异步io爬steam，几乎无间隔，steam也没有采取什么措施，估计服务器比较强，对这种小批量的爬不在乎
