### ISSUE TITLE
直接获取人民币的steam历史价格

### ISSUE THREAD

**Issue by mocap55551** [puppylpg/oddish#74]
# 建议描述
找到了一个网页，和您介绍里的一样，是人民币版的steam的price_history，您可以优化下改成直接获取人民币的数据，这样也不用去调汇率了，附上链接https://buff.163.com/api/market/goods/price_history?game=csgo&goods_id=759524&currency=CNY

**Comment by puppylpg** [comment]
多谢
不过这个我知道，一开始写代码的时候也是从buff上获取的steam历史售价，参见：https://github.com/puppylpg/oddish/blob/4eec549414f077cf83d95784b62ecfcf8cd65494/src/config/urls.py#L30

后来换成从steam获取价格了，参见 #11
