### ISSUE TITLE
关于dota2饰品的加入

### ISSUE THREAD

**Issue by duhl1999** [puppylpg/oddish#75]
# 建议描述
近期csgo挂刀比例很不理想，基本只能达到八五折挂刀
请问大佬是否有打算加入dota2饰品的挂刀比例的爬取
csgo挂刀实在不理想

**Comment by puppylpg** [comment]
没有打算，因为不玩DOTA2 😸 
如果可以欢迎提相关pull request，或者根据该版本复刻出一个dota版
