### ISSUE TITLE
印花好像不在category里

### ISSUE THREAD

**Issue by jiey2** [puppylpg/oddish#8]
印花好像不爬，也不在category里。

**Comment by puppylpg** [comment]
印花貌似就叫"sticker"，你可以试一下。一开始好像印花是在另一个类别里的，具体不是是csgo_type_collectible我记不清了，现在buff貌似把它独立出来了。

主要是buff买印花在steam里换余额不好卖，销量也不高，而且印花种类过多，爬起来很费时间，所以我一开始是挺想把印花整体删除的，和换steam余额的理念不符合
