### ISSUE TITLE
输入 -m src 以后，只是重复上一次爬虫的结果，快速的跑一遍只花了10秒钟，但是结果都是上一次的结果。

### ISSUE THREAD

**Issue by Jason-3885** [puppylpg/oddish#81]
# 问题描述
输入 -m src 以后，只是重复上一次爬虫的结果，快速的跑一遍只花了10秒钟，但是结果都是上一次的结果。
# 复现步骤

# 报错信息

# 相关截屏（最好贴一下）

# 软件信息
请完善以下信息：
- python版本：
- oddish版本（tag或者commit id）： 比如v3.6.1或者b3fcf3be37ecf58c955904a258f97a66b01b0db6；
- 操作系统：比如Windows 10；

**Comment by ccinv** [comment]
这是缓存系统正常的行为。如果要关闭缓存的使用，可以在config里面吧FORCE_CRAWL打开

**Comment by Jason-3885** [comment]
把FALSE改成TURE是么

**Comment by ccinv** [comment]
> 把FALSE改成TURE是么

是的

**Comment by ccinv** [comment]
> 把FALSE改成TURE是么

TRUE
...
