### ISSUE TITLE
大佬，刚刚入手这个工具，先借用这个工具做AI算法分析CSGO饰品价格并且做出预测

### ISSUE THREAD

**Issue by GUO-RUI-China** [puppylpg/oddish#95]
# 问题描述
大佬，刚刚入手这个工具，先借用这个工具做AI算法分析CSGO饰品价格并且做出预测，但是没怎么接触过JSON，想问下你这个工具怎么使用
# 复现步骤
![image](https://user-images.githubusercontent.com/67194749/132368721-e7b36f6a-44da-4b10-aa6c-8d9ec479ff88.png)
想问下这个图片里面哪个是安装界面没有找到.exe活着.out文件，大佬们能编译链接一下然后做成个.exe文件嘛

**Comment by ccinv** [comment]
https://github.com/puppylpg/oddish/releases/tag/4.2.0
可执行文件在这里
